apiVersion: apps/v1
kind: Deployment
metadata:
  name: km-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: km-demo-app
  template:
    metadata:
      labels:
        app: km-demo-app
    spec:
      containers:
        - name: app
          image: kaneofthrones/demo-app:1080
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: km-demo-app
spec:
  selector:
    app: km-demo-app
  ports:
    - name: "http" 
      port: 80
      targetPort: 80
  type: LoadBalancer
